M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2026-01-18T18:19:28+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-18T18:19:28+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X175.795Y-58.81
X180.745Y-53.86
M30
