M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu24.04.1} date 2025-11-05T21:41:06+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-05T21:41:06+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X175.66Y-58.68
X180.61Y-53.73
M30
